### ISSUE TITLE
Issues updating to apiextensions.k8s.io/v1 spec

### ISSUE THREAD

**Issue by endersonmaia** [technosophos/rust-k8s-controller#6]
I've applied this patch but I'm failing to run the controller.

```patch
diff --git a/docs/crd.yaml b/docs/crd.yaml
index 7eb0840..dff5dc0 100644
--- a/docs/crd.yaml
+++ b/docs/crd.yaml
@@ -1,4 +1,5 @@
-apiVersion: apiextensions.k8s.io/v1beta1
+---
+apiVersion: apiextensions.k8s.io/v1
 kind: CustomResourceDefinition
 metadata:
   name: books.example.technosophos.com
@@ -8,8 +9,21 @@ spec:
     - name: v1
       served: true
       storage: true
+      schema:
+        openAPIV3Schema:
+          type: object
+          properties:
+            spec:
+              type: object
+              properties:
+                title:
+                  type: string
+                authors:
+                  type: array
+                  items:
+                    type: string
   scope: Namespaced
   names:
     plural: books
     singular: book
-    kind: Book
\ No newline at end of file
+    kind: Book
```

Output of `cargo run`:

```shell
RUST_BACKTRACE=full
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/k8s-controller`
thread 'main' panicked at 'informer init failed: Error { inner: Error(Hyper(Error(Connect, Os { code: 22, kind: InvalidInput, message: "Invalid argument" })), "https://kubernetes.docker.internal:6443/apis/example.technosophos.com/v1/namespaces/default/books?&limit=1")

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h839035f844ea72e0 (0x563968e01a39)
             at src/backtrace/internal.rs:44
   1: failure::backtrace::Backtrace::new::h66aeb26ba4096224 (0x563968e014c8)
             at src/backtrace/mod.rs:111
   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h7e7b74cb002a7fe4 (0x5639687e5add)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
   3: <failure::error::Error as core::convert::From<F>>::from::he2eea6b5ea218bfa (0x5639687ea7a2)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
   4: <T as core::convert::Into<U>>::into::hb711b7f4db63a0a5 (0x5639687ef6de)
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/convert/mod.rs:726
   5: failure::context::Context<D>::with_err::h5b9bb809501380b1 (0x5639687e49b4)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/context.rs:105
   6: failure::Fail::context::hece4a51486500428 (0x5639687f672f)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/lib.rs:160
   7: <core::result::Result<T,E> as failure::result_ext::ResultExt<T,E>>::context::{{closure}}::hc8f8ffb8c17456c5 (0x56396880b87a)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/result_ext.rs:164
   8: core::result::Result<T,E>::map_err::hf6e48027a4f5bb5d (0x5639687fb7df)
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:861
   9: <core::result::Result<T,E> as failure::result_ext::ResultExt<T,E>>::context::h9eca80281db22225 (0x5639687fe2c2)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/result_ext.rs:164
  10: kube::client::APIClient::send::h5c00f36a8348b373 (0x5639687e6d73)
             at src/client/mod.rs:84
  11: kube::client::APIClient::request::h86bbb41745c19b97 (0x5639687cdb38)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.12.0/src/client/mod.rs:92
  12: kube::api::informer::Informer<K>::get_resource_version::h9f0a8cd15da7e1f2 (0x56396879432a)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.12.0/src/api/informer.rs:177
  13: kube::api::informer::Informer<K>::init::hab4594c2a976b96d (0x563968794c29)
             at /home/endersonmaia/.cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.12.0/src/api/informer.rs:114
  14: k8s_controller::main::hcf5dcc03cc3acad8 (0x5639687cc68d)
             at src/main.rs:36
  15: core::ops::function::FnOnce::call_once::h73be56a6235d0216 (0x5639687b42eb)
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507
  16: std::sys_common::backtrace::__rust_begin_short_backtrace::h0ad82d4f273ceef7 (0x56396879ce0e)
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:121
  17: std::rt::lang_start::{{closure}}::ha3f80a89c474b469 (0x5639687cb681)
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:166
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h9ab31282e87f134a (0x563968e42d2c)
             at library/core/src/ops/function.rs:606
      std::panicking::try::do_call::h42ddf5b01d0b4bc7
             at library/std/src/panicking.rs:483
      std::panicking::try::hfb70320d7386c61a
             at library/std/src/panicking.rs:447
      std::panic::catch_unwind::h978c9edbad2bb4d4
             at library/std/src/panic.rs:137
      std::rt::lang_start_internal::{{closure}}::h04ede5bd2f26b553
             at library/std/src/rt.rs:148
      std::panicking::try::do_call::ha6b9da35a0885c93
             at library/std/src/panicking.rs:483
      std::panicking::try::h3325520cab3a642e
             at library/std/src/panicking.rs:447
      std::panic::catch_unwind::h160beec6f047175b
             at library/std/src/panic.rs:137
      std::rt::lang_start_internal::h79190e3a877a769d
             at library/std/src/rt.rs:148
  19: std::rt::lang_start::h79c926ee8e426cca (0x5639687cb65a)
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:165
  20: main (0x5639687ccc3e)
  21: <unknown> (0x7f69a4db4d90)
  22: __libc_start_main (0x7f69a4db4e40)
  23: _start (0x56396876e4c5)
  24: <unknown> (0x0)

Error executing request }', src/main.rs:38:10
stack backtrace:
   0:     0x563968e4b14a - std::backtrace_rs::backtrace::libunwind::trace::h34aec3ef6cd8ad7e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x563968e4b14a - std::backtrace_rs::backtrace::trace_unsynchronized::h8035d38698d0f7a8
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563968e4b14a - std::sys_common::backtrace::_print_fmt::hff968f6695a1ba22
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x563968e4b14a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7eea0efe77acf1ec
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x563968e6cd7e - core::fmt::write::hc553f17407eb0b48
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
   5:     0x563968e46675 - std::io::Write::write_fmt::h62e5f01a089f48c0
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
   6:     0x563968e4af15 - std::sys_common::backtrace::_print::h52d116aff3db4cd1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x563968e4af15 - std::sys_common::backtrace::print::h9e7d2f98fb7af075
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x563968e4c6ff - std::panicking::default_hook::{{closure}}::hf74999dab2d0a95c
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
   9:     0x563968e4c43b - std::panicking::default_hook::hc11ca7d10c44c42f
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
  10:     0x563968e4ce0c - std::panicking::rust_panic_with_hook::hdb4da1ae79c845a5
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:688:13
  11:     0x563968e4cba9 - std::panicking::begin_panic_handler::{{closure}}::h02b5b35b126d5cf2
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:579:13
  12:     0x563968e4b5fc - std::sys_common::backtrace::__rust_end_short_backtrace::h6c6853376cf416d1
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x563968e4c8b2 - rust_begin_unwind
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
  14:     0x56396876de53 - core::panicking::panic_fmt::hfd9e949092070b66
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
  15:     0x56396876e2e3 - core::result::unwrap_failed::h4d34d8346233eb49
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
  16:     0x56396879afa0 - core::result::Result<T,E>::expect::h5089c233c7428772
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1070:23
  17:     0x5639687cc6b7 - k8s_controller::main::hcf5dcc03cc3acad8
                               at /home/endersonmaia/Development/rust/rust-k8s-controller/src/main.rs:36:20
  18:     0x5639687b42eb - core::ops::function::FnOnce::call_once::h73be56a6235d0216
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
  19:     0x56396879ce0e - std::sys_common::backtrace::__rust_begin_short_backtrace::h0ad82d4f273ceef7
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:121:18
  20:     0x5639687cb681 - std::rt::lang_start::{{closure}}::ha3f80a89c474b469
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:166:18
  21:     0x563968e42d2c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h9ab31282e87f134a
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:606:13
  22:     0x563968e42d2c - std::panicking::try::do_call::h42ddf5b01d0b4bc7
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  23:     0x563968e42d2c - std::panicking::try::hfb70320d7386c61a
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  24:     0x563968e42d2c - std::panic::catch_unwind::h978c9edbad2bb4d4
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  25:     0x563968e42d2c - std::rt::lang_start_internal::{{closure}}::h04ede5bd2f26b553
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:48
  26:     0x563968e42d2c - std::panicking::try::do_call::ha6b9da35a0885c93
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
  27:     0x563968e42d2c - std::panicking::try::h3325520cab3a642e
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
  28:     0x563968e42d2c - std::panic::catch_unwind::h160beec6f047175b
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
  29:     0x563968e42d2c - std::rt::lang_start_internal::h79190e3a877a769d
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:20
  30:     0x5639687cb65a - std::rt::lang_start::h79c926ee8e426cca
                               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:165:17
  31:     0x5639687ccc3e - main
  32:     0x7f69a4db4d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  33:     0x7f69a4db4e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  34:     0x56396876e4c5 - _start
  35:                0x0 - <unknown>

```

**Comment by endersonmaia** [comment]
a lot have changed since, so I'm closing this
